mode = "dark"

accent               = "#66FF66"
selection            = "#114411"
muted                = "#22AA22"
background           = "#050805"
dark_background      = "#030503"
darker_background    = "#000000"
lighter_background   = "#0E160E"
foreground           = "#33FF33"
dark_foreground      = "#22AA22"
light_foreground     = "#88FF88"
bright_foreground    = "#CCFFCC"
red                  = "#FF4466"
yellow               = "#FFFF33"
orange               = "#FF7722"
green                = "#33FF33"
cyan                 = "#44FFFF"
blue                 = "#66AAFF"
magenta              = "#EE44EE"
brown                = "#885500"
bright_red           = "#FF7799"
bright_yellow        = "#FFFF99"
bright_green         = "#99FF99"
bright_cyan          = "#99FFFF"
bright_blue          = "#99CCFF"
bright_magenta       = "#FF88FF"
selection_background = "#114411"
selection_foreground = "#CCFFCC"
